# Generated by Django 5.0.2 on 2024-02-20 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0002_devicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.ForeignKey(limit_choices_to={'device_type': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugin.devicetype')}, on_delete=django.db.models.deletion.CASCADE, to='ugin.devicemodel')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugin.devicetype')),
            ],
        ),
    ]
