# Generated by Django 5.0.2 on 2024-02-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0004_alter_device_options_alter_device_device_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
    ]
