# Generated by Django 5.0.2 on 2024-02-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0005_alter_device_options_remove_device_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.CharField(max_length=200)),
                ('SN', models.CharField(max_length=200)),
                ('IP', models.CharField(max_length=200)),
                ('MAC', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('ports_number', models.CharField(max_length=200)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugin.device')),
            ],
        ),
    ]
