# Generated by Django 5.0.2 on 2024-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0006_parametr'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametr',
            name='antenna_height',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='parametr',
            name='azimut',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='parametr',
            name='camera_number',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='parametr',
            name='comment',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='parametr',
            name='microphone',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='parametr',
            name='view',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='IP',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='MAC',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='SN',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='online',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='ports_number',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='role',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
