# Generated by Django 5.0.2 on 2024-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0007_parametr_antenna_height_parametr_azimut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametr',
            name='online',
            field=models.BooleanField(default=None),
        ),
    ]
