# Generated by Django 5.0.2 on 2024-02-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0008_alter_parametr_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametr',
            name='ports_number',
            field=models.IntegerField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='view',
            field=models.IntegerField(default=None, max_length=200),
        ),
    ]
