# Generated by Django 5.0.2 on 2024-02-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0009_alter_parametr_ports_number_alter_parametr_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametr',
            name='ports_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='view',
            field=models.IntegerField(default=None),
        ),
    ]
