# Generated by Django 5.0.2 on 2024-02-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0010_alter_parametr_ports_number_alter_parametr_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='parameters',
            field=models.ManyToManyField(to='ugin.parametr'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugin.devicetype'),
        ),
    ]
