# Generated by Django 5.0.2 on 2024-02-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0011_devicemodel_parameters_alter_parametr_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypeParametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametr_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='parameters',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='parameters',
            field=models.ManyToManyField(to='ugin.devicetypeparametr'),
        ),
    ]
