# Generated by Django 5.0.2 on 2024-02-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0012_devicetypeparametr_remove_devicemodel_parameters_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametr',
            new_name='DeviceParametr',
        ),
    ]
