# Generated by Django 5.0.2 on 2024-02-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0014_rename_devicetypeparametr_parametr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceParametr',
        ),
    ]
