# Generated by Django 5.0.2 on 2024-02-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0016_parametr_parametr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ugin.devicetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='parametrs',
            field=models.JSONField(default=None),
        ),
    ]
