# Generated by Django 5.0.2 on 2024-02-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugin', '0018_rename_parameters_devicetype_parametr_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_model',
            field=models.CharField(choices=[], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='parametr_type',
            field=models.CharField(choices=[('int', 'int'), ('str', 'str'), ('bool', 'bool')], default=None, max_length=200),
        ),
    ]
